---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
    driver_config:
      box: trusty-server-cloudimg
      box_url: https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box

suites:
  - name: server
    run_list:
      - recipe[seafile::server]
    attributes:
